"""Rebuild the Haukland coast DEM module (Python 3, Pillow and NumPy).

Source: Mapzen/Terrarium terrain tiles, Norwegian terrain data © Kartverket,
CC BY 4.0. This creates a resampled, quantized geographic reference, not a scan.
Run: python scripts/generate-coast-dem.py --cache path/to/tile-cache
"""
from __future__ import annotations

import argparse
import base64
import concurrent.futures
import hashlib
import json
import math
import pathlib
import tempfile
import urllib.request

import numpy as np
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parents[1]
ZOOM, X0, X1, Y0, Y1 = 14, 8805, 8809, 3894, 3899
LATITUDE, LONGITUDE = 68.200, 13.532


def varint(value: int, out: bytearray) -> None:
    while value > 127:
        out.append((value & 127) | 128)
        value >>= 7
    out.append(value)


def encode(values: np.ndarray) -> bytes:
    """Unsigned token: 0 = repeat previous value; otherwise zigzag(delta)+1."""
    packed = bytearray()
    previous, i = 0, 0
    flat = values.ravel()
    while i < len(flat):
        value = int(flat[i])
        if value == previous:
            end = i + 1
            while end < len(flat) and int(flat[end]) == previous:
                end += 1
            varint(0, packed)
            varint(end - i, packed)
            i = end
        else:
            delta = value - previous
            zigzag = delta * 2 if delta >= 0 else -delta * 2 - 1
            varint(zigzag + 1, packed)
            previous = value
            i += 1
    return bytes(packed)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--cache', type=pathlib.Path, default=pathlib.Path(tempfile.gettempdir()) / 'roam-earth-coast-dem')
    args = parser.parse_args()
    args.cache.mkdir(parents=True, exist_ok=True)
    mosaic = np.zeros(((Y1 - Y0 + 1) * 256, (X1 - X0 + 1) * 256), np.float32)
    sources = []

    def tile(coordinate: tuple[int, int]):
        x, y = coordinate
        url = f'https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{ZOOM}/{x}/{y}.png'
        path = args.cache / f'{ZOOM}-{x}-{y}.png'
        if not path.exists():
            with urllib.request.urlopen(url, timeout=60) as response:
                path.write_bytes(response.read())
        raw = path.read_bytes()
        rgb = np.asarray(Image.open(path).convert('RGB'), np.float32)
        height = rgb[:, :, 0] * 256 + rgb[:, :, 1] + rgb[:, :, 2] / 256 - 32768
        return x, y, height, {'url': url, 'sha256': hashlib.sha256(raw).hexdigest()}

    with concurrent.futures.ThreadPoolExecutor(max_workers=6) as pool:
        for x, y, height, source in pool.map(tile, [(x, y) for y in range(Y0, Y1 + 1) for x in range(X0, X1 + 1)]):
            mosaic[(y - Y0) * 256:(y - Y0 + 1) * 256, (x - X0) * 256:(x - X0 + 1) * 256] = height
            sources.append(source)

    # Retain source samples; quantize to 0.1 m. No vertical exaggeration is applied.
    elevation = np.round(np.maximum(0, mosaic[::2, ::2]) * 10).astype(np.uint16)
    raw = encode(elevation)
    blob = base64.b64encode(raw).decode('ascii')
    metres_per_source_pixel = 2 * math.pi * 6378137 * math.cos(math.radians(LATITUDE)) / (2 ** ZOOM * 256)
    origin_u = ((LONGITUDE + 180) / 360 * 2 ** ZOOM - X0) * 256
    origin_v = ((1 - math.asinh(math.tan(math.radians(LATITUDE))) / math.pi) / 2 * 2 ** ZOOM - Y0) * 256
    metadata = {
        'width': int(elevation.shape[1]), 'height': int(elevation.shape[0]),
        'step': metres_per_source_pixel * 2,
        'minX': (-origin_u + .5) * metres_per_source_pixel,
        'minZ': (-origin_v + .5) * metres_per_source_pixel,
        'latitude': LATITUDE, 'longitude': LONGITUDE,
    }
    chunks = '\n  + '.join(json.dumps(blob[i:i + 160]) for i in range(0, len(blob), 160))
    source = '''// GENERATED by scripts/generate-coast-dem.py. Do not edit the packed samples.
// Norwegian terrain data © Kartverket (CC BY 4.0), via Mapzen/Terrarium.
// East = +X, south = +Z; local metres around 68.200 N, 13.532 E.
export const coastDem = META as const;
const packed = PACKED;
let heights: Uint16Array | undefined;
export function coastElevations(): Uint16Array {
  if (heights) return heights;
  const bytes = atob(packed);
  let cursor = 0, index = 0, previous = 0;
  const read = () => { let value = 0, shift = 0, byte: number;
    do { byte = bytes.charCodeAt(cursor++); value |= (byte & 127) << shift; shift += 7; } while (byte & 128);
    return value;
  };
  const result = new Uint16Array(coastDem.width * coastDem.height);
  while (index < result.length) {
    const token = read();
    if (token === 0) { const count = read(); result.fill(previous, index, index + count); index += count; }
    else { const delta = token - 1; previous += (delta >>> 1) ^ -(delta & 1); result[index++] = previous; }
  }
  heights = result;
  return result;
}
export function sampleCoastElevation(x: number, z: number): number {
  const values = coastElevations();
  const u = Math.max(0, Math.min(coastDem.width - 1.001, (x - coastDem.minX) / coastDem.step));
  const v = Math.max(0, Math.min(coastDem.height - 1.001, (z - coastDem.minZ) / coastDem.step));
  const ix = Math.floor(u), iz = Math.floor(v), fx = u - ix, fz = v - iz;
  const a = iz * coastDem.width + ix;
  return ((values[a] * (1 - fx) + values[a + 1] * fx) * (1 - fz)
    + (values[a + coastDem.width] * (1 - fx) + values[a + coastDem.width + 1] * fx) * fz) * .1;
}
'''.replace('META', json.dumps(metadata, separators=(',', ':'))).replace('PACKED', chunks)
    target = ROOT / 'src' / 'scenes' / 'coast-dem.ts'
    target.write_text(source, encoding='utf-8')
    manifest = {
        'name': 'Haukland–Mannen coastal terrain reference', 'region': 'Vestvågøy, Lofoten, Norway',
        'attribution': 'Norwegian terrain data © Kartverket, via Mapzen/Terrarium terrain tiles.',
        'license': 'CC BY 4.0 (Norwegian Kartverket terrain source)',
        'licenseUrl': 'https://creativecommons.org/licenses/by/4.0/',
        'sourceAttributionDocumentation': 'https://github.com/tilezen/joerd/blob/master/docs/attribution.md',
        'datasetDocumentation': 'https://registry.opendata.aws/terrain-tiles/',
        'sourceResolutionNote': 'Norwegian terrain source is a 10 m DTM; zoom 14 delivery pixels are finer resampled pixels, not new survey precision.',
        'transformations': ['Mosaicked 30 zoom-14 Terrarium tiles', 'Retained every second source pixel', 'Quantized elevation to 0.1 m; clipped negative ocean cells to zero', 'Delta and run-length encoded for synchronous local loading', 'Scene adds artistic coastal bathymetry, small erosion details and shoreline props; these additions are not survey measurements'],
        'verticalExaggeration': 1, 'localCoordinates': metadata,
        'gridSamples': int(elevation.size), 'packedBytes': len(raw),
        'packedSha256': hashlib.sha256(raw).hexdigest(),
        'decodedSha256': hashlib.sha256(elevation.astype('<u2').tobytes()).hexdigest(), 'tiles': sources,
    }
    destination = ROOT / 'public' / 'terrain'
    destination.mkdir(parents=True, exist_ok=True)
    (destination / 'coast-sources.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding='utf-8')
    print(json.dumps({'module': str(target), 'samples': int(elevation.size), 'packedBytes': len(raw), 'moduleBytes': len(source), 'metadata': metadata}, indent=2))


if __name__ == '__main__':
    main()
